# Generated by Django 3.1.7 on 2021-03-31 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210331_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='likes',
            new_name='likers',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='scraps',
            new_name='scrapers',
        ),
    ]
